apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperopt-worker-deployment
  labels:
    app: hyperopt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperopt
  template:
    metadata:
      labels:
        app: hyperopt
    spec:
      containers:
      - name: hyperopt-worker
        image: registry.gitlab.com/lambda-hse/registry/hyperoptworker
        imagePullPolicy: Always
        resources:
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "16Gi"
            cpu: "8"
      imagePullSecrets:
      - name: gitlab-auth
